---
- name: Setup Debian Install
  hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Updating apt
      ansible.builtin.apt:
        update_cache: yes
    - name: Install packages
      ansible.builtin.apt:
        name: ['bridge-utils', 'cifs-utils', 'curl', 'dmg2img', 'ffmpeg', 'gimp', 'git', 'gparted', 'grub-customizer', 'gnome-shell-extensions', 'gnome-shell-extension-manager', 'gnome-tweaks', 'htop', 'libvirt-daemon-system', 'libvirt-clients', 'neovim', 'openjdk-17-jdk', 'openjdk-17-jre', 'ovmf', 'python3', 'qemu-kvm', 'qemu-utils', 'steam', 'virt-manager', 'vlc', 'wine']
        force_apt_get: true
    - name: Enable IOMMU
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="((:?(?!amd_iommu=on).)*?)"$'
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash udev.log_priority=3 amd_iommu=on iommu=pt iommu=1"'
        backup: true
        backrefs: true
    - name: Update GRUB
      command: grub-mkconfig -o /boot/grub/grub.cfg
    - name: Rebooting
      command: reboot now

