---
- name: Setup Arch Linux environment
  hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Install packages
      community.general.pacman:
        name: ['steam', 'vivaldi', 'discord', 'neovim', 'code', 'gimp', 'libvirt', 'qemu', 'bridge-utils', 'vde2', 'virt-manager', 'jre-openjdk']
        state: latest
    - name: Enable IOMMU
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="((:?(?!amd_iommu=on).)*?)"$'
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash udev.log_priority=3 amd_iommu=on iommu=pt iommu=1"'
        backup: true
        backrefs: true
    - name: Update GRUB
      command: grub-mkconfig -o /boot/grub/grub.cfg
    - name: Rebooting
      command: reboot now
