---
- name: Setup Arch Linux environment
  hosts: all
  become: yes

  tasks:
    - name: Install packages
        community.general.pacman:
            name: ['steam', 'vivaldi', 'discord', 'neovim', 'code', 'gimp', 'libvirt', 'qemu', 'bridge-utils', 'vde2', 'virt-manager', 'jre-openjdk']
            state: latest
    - name: Enable IOMMU
          ansible.builtin.lineinfile:
            path: /etc/default/grub
            regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="((:?(?!amd_iommu=on).)*?)"$'
            line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 amd_iommu=on iommu=pt iommu=1"'
          backup: true
          backrefs: true
        notify:
          - Update GRUB
    - name: Update GRUB
        command: grub-mkconfig -o /boot/grub/grub.cfg
    - name: Rebooting
        ansible.builtin.reboot:
