---
- hosts: all
  become: true
  tasks:

    - name: Installing packages without differing names
      package:
        name: ['bridge-utils', 'curl', 'gimp', 'git', 'htop', 'wget', 'zsh']
        state: latest

# Runs on distros with Pacman
    - name: Install pacman packages
      pacman:
          name:
            - steam
            - discord
            - neovim
            - code
            - gimp
            - libvirt
            - qemu
            - vde2
            - virt-manager
            - jre-openjdk
            - vivaldi
            - nvtop
          state: latest
      when: ansible_distribution in ["Archlinux", "Manjaro"]

# Runs on distros with apt
    - name: Install apt packages
      apt:
        pkg:
          - cifs-utils
          - gparted
          - grub-customizer
          - gnome-shell-extensions
          - gnome-shell-extension-manager
          - gnome-tweaks
          - libvirt-daemon-system
          - libvirt-clients
          - neovim
          - openjdk-17-jdk
          - openjdk-17-jre
          - ovmf
          - python3
          - qemu-kvm
          - qemu-utils
          - steam
          - virt-manager
          - vlc
          - wine
        state: latest
        update_cache: yes
      when: ansible_distribution in ["Ubuntu", "Kubuntu", "Debian"]

# Runs regardless
    - name: Enable IOMMU
      lineinfile:
          path: /etc/default/grub
          regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="((:?(?!amd_iommu=on).)*?)"$'
          line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 amd_iommu=on iommu=pt iommu=1"'
          backup: true
          backrefs: true
      when: ansible_form_factor == "Desktop"

    - name: Update GRUB
      command: grub-mkconfig -o /boot/grub/grub.cfg
      when: ansible_form_factor == "Desktop"

    - name: Starting Virsh Internet connection
      shell: virsh net-start default && virsh net-autostart default
      when: ansible_form_factor == "Desktop"

    - name: Adding qemu/kvm groups
      shell: usermod -aG kvm,input,libvirt david
      when: ansible_form_factor == "Desktop"

    - name: Copying Libvirt hooks script into place
      copy:
        src: "{{ inventory_dir | dirname }}/hooks"
        dest: /etc/libvirt/hooks
        owner: david
        group: kvm
        mode: u=rwx,g=rwx,o=r
      when: ansible_form_factor == "Desktop"

    - name: Creating vgabios directory
      shell: mkdir /usr/share/vgabios
      when: ansible_form_factor == "Desktop"

    - name: Copying GPU vBIOS ROM into place
      copy:
        src: "/etc/libvirt/hooks/GPU.rom"
        dest: "/usr/share/vgabios"
      when: ansible_form_factor == "Desktop"

    - name: Grabbing dotfiles
      shell: git clone https://github.com/Master449/.dotfiles.git /home/david/.dotfiles
      become_user: david

    - name: Placing .zshrc
      file:
        src: /home/david/.dotfiles/.zshrc
        dest: /home/david/.zshrc
        owner: david
        group: david
        state: link

    - name: Placing .zsh_aliases
      file:
        src: /home/david/.dotfiles/.zsh_aliases
        dest: /home/david/.zsh_aliases
        owner: david
        group: david
        state: link

    - name: Placing .gitconfig
      file:
        src: /home/david/.dotfiles/.gitconfig
        dest: /home/david/.gitconfig
        owner: david
        group: david
        state: link

    - name: Changing default shell
      user:
        name: david
        shell: /bin/zsh
    
    - name: Create fonts directory if it doesn't exist
      file:
        path: /home/david/.fonts
        state: directory

    - name: Download JetBrains Mono Nerd Font
      get_url:
        url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/JetBrainsMono.zip"
        dest: "/tmp/JetBrainsMono.zip"
        mode: 0644

    - name: Unzip JetBrains Mono Nerd Font
      unarchive:
        src: /tmp/JetBrainsMono.zip
        dest: /home/david/.fonts
        remote_src: true
        extra_opts: --junk-paths
        creates: /home/david/.fonts/JetBrainsMono-Regular.ttf

    - name: Refresh font cache
      shell: fc-cache -f -v
      become_user: david
