---
- hosts: all
  become: yes
  tasks:

# Runs on distros with Pacman
    - name: Install pacman packages
      pacman:
          name: ['bridge-utils', 'steam', 'discord', 'neovim', 'code', 'gimp', 'git', 'libvirt', 'qemu', 'vde2', 'virt-manager', 'jre-openjdk', 'vivaldi']
          state: latest
      when: ansible_distribution in ["Arch", "Manjaro"]

# Runs on distros with apt
    - name: Install apt packages
      pacman:
          name:  ['bridge-utils', 'cifs-utils', 'curl', 'gimp', 'git', 'gparted', 'grub-customizer', 'gnome-shell-extensions', 'gnome-shell-extension-manager', 'gnome-tweaks', 'htop', 'libvirt-daemon-system', 'libvirt-clients', 'neovim', 'openjdk-17-jdk', 'openjdk-17-jre', 'ovmf', 'python3', 'qemu-kvm', 'qemu-utils', 'steam', 'virt-manager', 'vlc', 'wine']
          state: latest
        when: ansible_distribution in ["Ubuntu", "Kubuntu", "Debian"]

# Runs regardless
    - name: Enable IOMMU
      lineinfile:
          path: /etc/default/grub
          regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="((:?(?!amd_iommu=on).)*?)"$'
          line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 amd_iommu=on iommu=pt iommu=1"'
      backup: true
      backrefs: true

    - name: Update GRUB
      command: grub-mkconfig -o /boot/grub/grub.cfg

# These commands make it so asnsible becomes my user to run these
    - name: Update git config name
      command: git config --global user.name "David Flowers II"
      become_user: david

    - name: Update git config email
      command: git config --global user.email "master4491@gmail.com"
      become_user: david

    - name: Update git config adog alias
      command: git config --global alias.adog "git log --all --decorate --oneline --graph"
      become_user: david

    - name: Add serve alias for foo user
      lineinfile:
        path: /home/david/.bash_aliases
        owner: david
        state: present
        line: "{{ item }}"
        create: true
      with_items:
      - "alias gs='git status'"
      - "alias gc='git commit'"
      - "alias gl='git log'"
      - "alias gp='git push'"
