---
- hosts: all
  become: yes
  tasks:

# Runs on distros with Pacman
    - name: Install pacman packages
        pacman:
          name: ['steam', 'vivaldi', 'discord', 'neovim', 'code', 'gimp', 'libvirt', 'qemu', 'bridge-utils', 'vde2', 'virt-manager', 'jre-openjdk']
          state: latest
        when: ansible_distribution in ["Arch", "Manjaro"]

# Runs on distros with apt
    - name: Install apt packages
        pacman:
          name:  ['bridge-utils', 'cifs-utils', 'curl', 'gimp', 'git', 'gparted', 'grub-customizer', 'gnome-shell-extensions', 'gnome-shell-extension-manager', 'gnome-tweaks', 'htop', 'libvirt-daemon-system', 'libvirt-clients', 'neovim', 'openjdk-17-jdk', 'openjdk-17-jre', 'ovmf', 'python3', 'qemu-kvm', 'qemu-utils', 'steam', 'virt-manager', 'vlc', 'wine']
          state: latest
        when: ansible_distribution in ["Ubuntu", "Kubuntu", "Debian"]

# Runs regardless
    - name: Enable IOMMU
        lineinfile:
          path: /etc/default/grub
          regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="((:?(?!amd_iommu=on).)*?)"$'
          line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 amd_iommu=on iommu=pt iommu=1"'
        backup: true
        backrefs: true

    - name: Update GRUB
        command: grub-mkconfig -o /boot/grub/grub.cfg
