---
- hosts: all
  become: true
  tasks:

    - name: Installing packages without differing names
      package:
        name: ['bridge-utils', 'curl', 'gimp', 'git', 'htop', 'wget']
        state: latest

# Runs on distros with Pacman
    - name: Install pacman packages
      pacman:
          name:
            - steam
            - discord
            - neovim
            - code
            - gimp
            - libvirt
            - qemu
            - vde2
            - virt-manager
            - jre-openjdk
            - vivaldi
            - nvtop
          state: latest
      when: ansible_distribution in ["Archlinux", "Manjaro"]

# Runs on distros with apt
    - name: Install apt packages
      apt:
        pkg:
          - cifs-utils
          - gparted
          - grub-customizer
          - gnome-shell-extensions
          - gnome-shell-extension-manager
          - gnome-tweaks
          - libvirt-daemon-system
          - libvirt-clients
          - neovim
          - openjdk-17-jdk
          - openjdk-17-jre
          - ovmf
          - python3
          - qemu-kvm
          - qemu-utils
          - steam
          - virt-manager
          - vlc
          - wine
        state: latest
        update_cache: yes
      when: ansible_distribution in ["Ubuntu", "Kubuntu", "Debian"]

# Runs regardless
    - name: Enable IOMMU
      lineinfile:
          path: /etc/default/grub
          regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="((:?(?!amd_iommu=on).)*?)"$'
          line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 amd_iommu=on iommu=pt iommu=1"'
          backup: true
          backrefs: true
      when: ansible_form_factor == "Desktop"

    - name: Update GRUB
      command: grub-mkconfig -o /boot/grub/grub.cfg
      when: ansible_form_factor == "Desktop"

# These commands make it so ansible becomes my user to run these
    - name: Update git config
      shell: |
        git config --global user.name "David Flowers II"
        git config --global user.email "master4491@gmail.com"
        git config --global alias.adog "log --all --decorate --oneline --graph"
      become_user: david

    - name: Add aliases to bash_aliases
      lineinfile:
        path: /home/david/.bash_aliases
        owner: david
        state: present
        line: "{{ item }}"
        create: true
      with_items:
      - "alias gs='git status'"
      - "alias gc='git commit'"
      - "alias gl='git log'"
      - "alias gp='git push'"
      - "alias gd='git adog'"
      - "alias ll='ls -Al --group-directories-first'"

    - name: Update bash with the new aliases
      shell: source ~/.bash_aliases
      become_user: david

    - name: Adding qemu/kvm groups
      shell: usermod -aG kvm,input,libvirt david

    - name: Creating Libvirt Hooks directories
      shell: mkdir -p /etc/libvirt/hooks/qemu.d/win10/prepare/begin && mkdir -p /etc/libvirt/hooks/qemu.d/win10/release/end

    - name: Creating vBIOS directories
      shell: mkdir /usr/share/vgabios

    - name: Copying Libvirt hooks script into place
      shell: cp $(pwd)/qemu /etc/libvirt/hooks/qemu.d/qemu

    - name: Copying Start scripts into place
      shell: cp $(pwd)/hooks/qemu.d/win10/prepare/begin/start.sh /etc/libvirt/hooks/qemu.d/win10/prepare/begin/start.sh

    - name: Copying Stop scripts into place
      shell: cp $(pwd)/hooks/qemu.d/win10/release/end/revert.sh /etc/libvirt/hooks/qemu.d/win10/release/end/revert.sh

    - name: Copying GPU vBIOS ROM into place
      shell: cp $(pwd)/GPU.rom /usr/share/vgabios/GPU.rom

    - name: Updating previous files permissions
      shell: chmod +x /etc/libvirt/hooks/qemu.d/win10/prepare/begin/start.sh && chmod +x /etc/libvirt/hooks/qemu.d/win10/release/end/revert.sh
